---
# Webserver handlers

- name: Restart webserver
  service:
    name: "{{ webserver_service }}"
    state: restarted
  become: yes

- name: Reload webserver
  service:
    name: "{{ webserver_service }}"
    state: reloaded
  become: yes