apiVersion: v2
name: myapp
description: A Helm chart for Kubernetes
type: application
version: 0.1.0
appVersion: "1.16.0"

dependencies:
- name: nginx
  version: "9.9.9"
  repository: "https://charts.bitnami.com/bitnami"