apiVersion: kubelet.config.k8s.io/v1beta1
kind: KubeletConfiguration
staticPodPath: "/etc/kubernetes/manifests"
syncFrequency: "1m0s"
fileCheckFrequency: "20s"
httpCheckFrequency: "20s"
address: "0.0.0.0"
port: 10250
readOnlyPort: 10255
tlsCertFile: "/var/lib/kubelet/pki/kubelet.crt"
tlsPrivateKeyFile: "/var/lib/kubelet/pki/kubelet.key"
authentication:
  anonymous:
    enabled: false
  webhook:
    enabled: true
  x509:
    clientCAFile: "/etc/kubernetes/pki/ca.crt"
authorization:
  mode: Webhook
clusterDNS:
  - "10.96.0.10"
clusterDomain: "cluster.local"
failSwapOn: true