apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- service.yaml

configMapGenerator:
- name: example-config
  literals:
  - DATABASE_HOST=localhost
  - DATABASE_PORT=5432

secretGenerator:
- name: example-secret
  literals:
  - USERNAME=admin
  - PASSWORD=password