---
# Webserver tasks

- name: Include OS-specific variables
  include_vars: "{{ ansible_os_family }}.yml"
  tags: [webserver, configuration]

- name: Install web server package
  package:
    name: "{{ webserver_package }}"
    state: present
  become: yes
  tags: [webserver, installation]

- name: Create web server configuration
  template:
    src: nginx.conf.j2
    dest: "{{ webserver_config_path }}"
    owner: root
    group: root
    mode: '0644'
  notify: Restart webserver
  become: yes
  tags: [webserver, configuration]

- name: Create sites directory
  file:
    path: "{{ item }}"
    state: directory
    owner: root
    group: root
    mode: '0755'
  loop:
    - "{{ webserver_sites_path }}"
    - "{{ webserver_enabled_sites_path }}"
  become: yes
  tags: [webserver, configuration]

- name: Create virtual host configuration
  template:
    src: site.conf.j2
    dest: "{{ webserver_sites_path }}/{{ app_name }}.conf"
    owner: root
    group: root
    mode: '0644'
  notify: Reload webserver
  become: yes
  tags: [webserver, configuration]

- name: Enable virtual host
  file:
    src: "{{ webserver_sites_path }}/{{ app_name }}.conf"
    dest: "{{ webserver_enabled_sites_path }}/{{ app_name }}.conf"
    state: link
  notify: Reload webserver
  become: yes
  tags: [webserver, configuration]

- name: Start and enable web server service
  service:
    name: "{{ webserver_service }}"
    state: started
    enabled: yes
  become: yes
  tags: [webserver, service]