---
# 安装Kibana任务

- name: 创建Kibana用户
  user:
    name: "{{ kibana_user }}"
    system: yes
    shell: /bin/false
    state: present
  tags: [logging, kibana, setup]

- name: 创建Kibana目录
  file:
    path: "{{ kibana_config_dir }}"
    state: directory
    owner: "{{ kibana_user }}"
    group: "{{ kibana_group }}"
    mode: '0755'
  tags: [logging, kibana, setup]

- name: 下载Kibana
  get_url:
    url: "https://artifacts.elastic.co/downloads/kibana/kibana-{{ kibana_version }}-linux-x86_64.tar.gz"
    dest: "/tmp/kibana-{{ kibana_version }}-linux-x86_64.tar.gz"
    mode: '0644'
  tags: [logging, kibana, download]

- name: 解压Kibana
  unarchive:
    src: "/tmp/kibana-{{ kibana_version }}-linux-x86_64.tar.gz"
    dest: "/tmp"
    remote_src: yes
  tags: [logging, kibana, extract]

- name: 复制Kibana二进制文件
  copy:
    src: "/tmp/kibana-{{ kibana_version }}/bin/kibana"
    dest: "/usr/local/bin/kibana"
    mode: '0755'
    remote_src: yes
  tags: [logging, kibana, install]

- name: 复制Kibana配置文件
  copy:
    src: "/tmp/kibana-{{ kibana_version }}/config/"
    dest: "{{ kibana_config_dir }}"
    owner: "{{ kibana_user }}"
    group: "{{ kibana_group }}"
    mode: '0644'
    remote_src: yes
  tags: [logging, kibana, install]

- name: 创建Kibana systemd服务文件
  template:
    src: kibana.service.j2
    dest: "{{ kibana_systemd_file }}"
    mode: '0644'
  tags: [logging, kibana, service]

- name: 重新加载systemd
  systemd:
    daemon_reload: yes
  tags: [logging, kibana, service]