---
# 安装Logstash任务

- name: 创建Logstash用户
  user:
    name: "{{ logstash_user }}"
    system: yes
    shell: /bin/false
    state: present
  tags: [logging, logstash, setup]

- name: 创建Logstash目录
  file:
    path: "{{ logstash_config_dir }}"
    state: directory
    owner: "{{ logstash_user }}"
    group: "{{ logstash_group }}"
    mode: '0755'
  tags: [logging, logstash, setup]

- name: 下载Logstash
  get_url:
    url: "https://artifacts.elastic.co/downloads/logstash/logstash-{{ logstash_version }}-linux-x86_64.tar.gz"
    dest: "/tmp/logstash-{{ logstash_version }}-linux-x86_64.tar.gz"
    mode: '0644'
  tags: [logging, logstash, download]

- name: 解压Logstash
  unarchive:
    src: "/tmp/logstash-{{ logstash_version }}-linux-x86_64.tar.gz"
    dest: "/tmp"
    remote_src: yes
  tags: [logging, logstash, extract]

- name: 复制Logstash二进制文件
  copy:
    src: "/tmp/logstash-{{ logstash_version }}/bin/logstash"
    dest: "/usr/local/bin/logstash"
    mode: '0755'
    remote_src: yes
  tags: [logging, logstash, install]

- name: 复制Logstash配置文件
  copy:
    src: "/tmp/logstash-{{ logstash_version }}/config/"
    dest: "{{ logstash_config_dir }}"
    owner: "{{ logstash_user }}"
    group: "{{ logstash_group }}"
    mode: '0644'
    remote_src: yes
  tags: [logging, logstash, install]

- name: 创建Logstash systemd服务文件
  template:
    src: logstash.service.j2
    dest: "{{ logstash_systemd_file }}"
    mode: '0644'
  tags: [logging, logstash, service]

- name: 重新加载systemd
  systemd:
    daemon_reload: yes
  tags: [logging, logstash, service]