apiVersion: batch/v1
kind: Job
metadata:
  name: "{{ .Release.Name }}-pre-install-hook"
  labels:
    app: {{ .Release.Name }}-pre-install-hook
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    metadata:
      name: "{{ .Release.Name }}-pre-install-hook"
      labels:
        app: {{ .Release.Name }}-pre-install-hook
    spec:
      restartPolicy: Never
      containers:
      - name: pre-install-job
        image: "busybox"
        command: ['sh', '-c', 'echo "Pre-install hook running..." && sleep 5 && echo "Pre-install hook completed!"']