---
# 安装Node Exporter任务

- name: 创建Node Exporter用户
  user:
    name: node_exporter
    system: yes
    shell: /bin/false
    state: present
  tags: [monitoring, node_exporter, setup]

- name: 下载Node Exporter
  get_url:
    url: "https://github.com/prometheus/node_exporter/releases/download/v{{ node_exporter_version }}/node_exporter-{{ node_exporter_version }}.linux-amd64.tar.gz"
    dest: "/tmp/node_exporter-{{ node_exporter_version }}.linux-amd64.tar.gz"
    mode: '0644'
  tags: [monitoring, node_exporter, download]

- name: 解压Node Exporter
  unarchive:
    src: "/tmp/node_exporter-{{ node_exporter_version }}.linux-amd64.tar.gz"
    dest: "/tmp"
    remote_src: yes
  tags: [monitoring, node_exporter, extract]

- name: 复制Node Exporter二进制文件
  copy:
    src: "/tmp/node_exporter-{{ node_exporter_version }}.linux-amd64/node_exporter"
    dest: "/usr/local/bin/node_exporter"
    mode: '0755'
    remote_src: yes
  tags: [monitoring, node_exporter, install]

- name: 创建Node Exporter systemd服务文件
  template:
    src: node_exporter.service.j2
    dest: /etc/systemd/system/node_exporter.service
    mode: '0644'
  tags: [monitoring, node_exporter, service]

- name: 重新加载systemd
  systemd:
    daemon_reload: yes
  tags: [monitoring, node_exporter, service]